---
title: "Extra"
---

## Tutorials

I recommend the following tutorials to revise the content of the workshop and for further details of fitting GAMs:

- S칩skuthy, M치rton. 2017. **Generalised additive mixed models for dynamic analysis in linguistics: a practical introduction.** <https://doi.org/10.48550/arXiv.1703.05339>
- S칩skuthy, M치rton. 2021. **Evaluating generalised additive mixed modelling strategies for dynamic speech analysis.** <https://doi.org/10.1016/j.wocn.2020.101017>
- Pedersen, Eric et al. 2019. **Hierarchical generalized additive models in ecology: an introduction with mgcv.** <https://doi.org/10.7717/peerj.6876>

See also:

- Tamminga, Meredith et al. 2016. **Generalized additive mixed models for intraspeaker variation**. <https://doi.org/10.1515/lingvan-2016-0030>
- Winter, Bodo et al. 2016. **How to analyze linguistic change using mixed models, growth curve analysis and generalized additive modeling**. <https://doi.org/10.1093/jole/lzv003>
- Wieling, Martijn. 2018. **Analyzing dynamic phonetic data using generalized additive mixed modeling: a tutorial focusing on articulatory differences between L1 and L2 speakers of English.** <https://www.sciencedirect.com/science/article/abs/pii/S0095447017301377>

Other tutorials.

- Noam, Ross. **GAMs in R: A free, interactive course using mgcv.** <https://noamross.github.io/gams-in-r-course/>
- Clark, Michael. **Generalised Additive Models.** <https://m-clark.github.io/generalized-additive-models/>

## Book

If you have an undergraduate degree in maths or similar (no joke!):

- Wood, Simon. 2017. **Generalized additive models: an introduction with R.** <https://www.taylorfrancis.com/books/mono/10.1201/9781315370279/generalized-additive-models-simon-wood>

## GAMs in linguistic research

Some linguistics papers that use GAMs:

- Coretta, Stefano. 2020. **Longer vowel duration correlates with greater tongue root advancement at vowel offset: acoustic and articulatory data from Italian and Polish.**. <https://asa.scitation.org/doi/10.1121/10.0000556>
- Cameron-Faulkner, Thea et al. 2020. **A cross-cultural analysis of early prelinguistic gesture development and its relationship to language development.** <https://doi.org/10.1111/cdev.13406>.
- Oschkinat, Miriam et al. 2020. **Compensation to real-time temporal auditory feedback perturbation depends on syllable position**. <https://doi.org/10.1121/10.0001765>
- Los, Bettelou et al. 2023. **The decline of local anchoring: A quantitative investigation**. <https://www.doi.org/10.1017/S1360674323000047>
- ...
